package dev.opencivitas.police;

public enum LawResult {
    SUCCESS,
    NOT_FOUND,
    PLAYER_NOT_FOUND,
    NOT_AUTHORIZED,
    NOT_REPORTER,
    INVALID_STATE,
    INVALID_CONTENT,
    NO_REPORTABLE_DEATH,
    ALREADY_REPORTED,
    ALREADY_ASSIGNED,
    ASSIGNED_TO_OTHER,
    OFFENSE_NOT_FOUND,
    NOT_WANTED,
    ALREADY_DETAINED,
    CLUE_UNAVAILABLE
}
