package dev.opencivitas.economy;

public enum LedgerEntryType {
    STARTING_BALANCE,
    PAYMENT,
    BUSINESS_TRANSFER,
    BUSINESS_PAYMENT,
    SHOP_PURCHASE,
    SHOP_SALE,
    CLAIM_BLOCK_PURCHASE,
    PROPERTY_PURCHASE,
    PROPERTY_RENT,
    PROPERTY_RENT_REFUND,
    PROPERTY_RENT_INCOME,
    AUCTION_BID,
    AUCTION_REFUND,
    AUCTION_PURCHASE,
    AUCTION_SALE,
    POLICE_FINE,
    MEDICARE_BENEFIT,
    PHARMACY_COPAY
}
