package dev.opencivitas.health;

public enum HealthResult {
    SUCCESS,
    CITIZEN_NOT_FOUND,
    CONDITION_NOT_FOUND,
    ALREADY_AFFECTED,
    NO_TREATABLE_CONDITION,
    NOT_DOCTOR,
    CALL_NOT_FOUND,
    CALL_ALREADY_CLAIMED,
    NO_MEDICARE_CLAIM,
    ACCOUNT_NOT_FOUND,
    INSUFFICIENT_FUNDS,
    PHARMACY_NOT_FOUND,
    NOT_PHARMACY_TREATMENT
}
