package dev.opencivitas.stock;

public enum StockResult {
    SUCCESS,
    CITIZEN_NOT_FOUND,
    BUSINESS_NOT_FOUND,
    BUSINESS_INACTIVE,
    EXCHANGE_NOT_FOUND,
    EXCHANGE_INACTIVE,
    EXCHANGE_EXISTS,
    LISTING_NOT_FOUND,
    LISTING_EXISTS,
    LISTING_PENDING,
    LISTING_INACTIVE,
    ORDER_NOT_FOUND,
    ORDER_NOT_OPEN,
    OPEN_ORDER_LIMIT,
    INSUFFICIENT_FUNDS,
    INSUFFICIENT_SHARES,
    INSUFFICIENT_BUSINESS_FUNDS,
    NO_SHAREHOLDERS,
    NO_PERMISSION,
    INVALID_VALUE
}
