package dev.opencivitas.legislature;

public enum LegislativeActionResult {
    SUCCESS,
    NOT_FOUND,
    NO_PERMISSION,
    INVALID_STATE,
    INVALID_CONTENT,
    NOT_AUTHOR,
    NOT_HOUSE_MEMBER,
    NOT_SENATE_MEMBER,
    NOT_PRESIDENT,
    PRESIDENTIAL_WINDOW_EXPIRED,
    ALREADY_TALLIED,
    QUORUM_FAILED,
    VOTE_FAILED,
    APPROPRIATION_OVERRIDE_FORBIDDEN,
    REFERENDUM_NOT_READY
}
