package dev.opencivitas.family;

public enum FamilyResult {
    SUCCESS,
    CITIZEN_NOT_FOUND,
    CANNOT_TARGET_SELF,
    ALREADY_FRIENDS,
    REQUEST_ALREADY_PENDING,
    REQUEST_NOT_FOUND,
    NOT_FRIENDS,
    ALREADY_MARRIED,
    PROPOSAL_ALREADY_PENDING,
    PROPOSAL_NOT_FOUND,
    PROPOSAL_NOT_ACCEPTED,
    NOT_LAWYER,
    NOT_MARRIED,
    NOT_SPOUSE,
    HOME_NOT_SET,
    INVALID_CONTENT
}
