package dev.opencivitas.election;

public enum ElectionActionResult {
    SUCCESS,
    NOT_FOUND,
    SLUG_EXISTS,
    INVALID_TIMELINE,
    INVALID_PHASE,
    NOT_ENDED,
    PLAYER_NOT_FOUND,
    RUNNING_MATE_REQUIRED,
    RUNNING_MATE_NOT_ALLOWED,
    RUNNING_MATE_SELF,
    RUNNING_MATE_NOT_FOUND,
    RUNNING_MATE_INELIGIBLE_CITIZENSHIP,
    RUNNING_MATE_INELIGIBLE_TOTAL_PLAYTIME,
    RUNNING_MATE_INELIGIBLE_RECENT_PLAYTIME,
    RUNNING_MATE_INELIGIBLE_HISTORY,
    ALREADY_NOMINATED,
    NOT_NOMINATED,
    INELIGIBLE_CITIZENSHIP,
    INELIGIBLE_TOTAL_PLAYTIME,
    INELIGIBLE_RECENT_PLAYTIME,
    INELIGIBLE_REELECTION,
    EMPTY_BALLOT,
    DUPLICATE_CHOICE,
    INVALID_CHOICE,
    ALREADY_CLOSED
}
