package dev.opencivitas.business;

public enum BusinessResult {
    SUCCESS,
    BUSINESS_NOT_FOUND,
    BUSINESS_INACTIVE,
    CITIZEN_NOT_FOUND,
    MISSING_QUALIFICATION,
    NAME_TAKEN,
    NO_PERMISSION,
    ALREADY_MEMBER,
    NOT_MEMBER,
    OFFER_EXISTS,
    OFFER_NOT_FOUND,
    INVALID_ROLE,
    ROLE_EXISTS,
    ROLE_LIMIT_REACHED,
    CANNOT_REMOVE_PROPRIETOR,
    INSUFFICIENT_PERSONAL_FUNDS,
    INSUFFICIENT_BUSINESS_FUNDS
}
